config/routes.rb
Rails.application.routes.draw do

  get 'breeds/index'
  get 'breeds/show'
  get 'owners/index'
  get 'owners/show'
  # get 'owner/index'
  # get 'owner/show'
  resources :dogs, only: [:index, :show]
  resources :owners, only: [:index, :show]
 # get 'dogs/index'
  # get 'dogs/show'
  #get 'index/show'

  root to: 'dogs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breed.rb
class Breed < ApplicationRecord
  has_many :dogs

  validates :name, :description, presence: true
end

app/models/dog.rb
class Dog < ApplicationRecord

  paginates_per 20

  validates :name, :image_url, :description, presence: true
  validates :age, numericality: { only_integer: true }, presence: true

  belongs_to :breed
  belongs_to :owner
end

app/models/owner.rb
class Owner < ApplicationRecord

  validates :name, :address, :profile_photo, presence: true
  validates :phone, length: { maximum: 10 }, presence: true
  has_many :dogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.order(:name).page params[:page]
  end

  def show
    @dog = Dog.find(params[:id])
  end
end

app/controllers/owner_controller.rb
class OwnerController < ApplicationController
  def index
    @owners = Owner.order(:name)
  end

  def show
    @owner = Owner.find(params[:id])
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.order(:name)
  end

  def show
    @owner = Owner.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/dogs_controller_helper.rb
module DogsControllerHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/owner_helper.rb
module OwnerHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/breeds/index.html.erb
<h1>Breeds#index</h1>
<p>Find me in app/views/breeds/index.html.erb</p>

app/views/breeds/show.html.erb
<h1>Breeds#show</h1>
<p>Find me in app/views/breeds/show.html.erb</p>

app/views/dogs/index.html.erb
<h1>Dogs#index</h1>

<ul>
  <% @dogs.each do |dog| %>
    <li><%= link_to dog.name, dog %></li>
  <% end %>
</ul>

<%= paginate @dogs %>

app/views/dogs/show.html.erb
<h1>Dogs#show</h1>

<h2><%= @dog.name %> is a <%= @dog.breed.name %> and belongs to <%= @dog.owner.name %></h2>
<p></p>

<img src=<%= @dog.image_url %> alt="doggo" height="auto" width="auto">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <h1>Welcome to Hogwarts</h1>
      <nav>
        <ul>
          <li><%= link_to 'Dogs', dogs_path %></li>
          <li><%= link_to 'Owners', owners_path %></li>
        </ul>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/owners/index.html.erb
<h1>Owners#index</h1>

<ul>
  <% @owners.each do |owner| %>
    <li><%= link_to owner.name, owner %></li>
  <% end %>
</ul>

app/views/owners/show.html.erb
<h1>Owners#show</h1>
<p>Find me in app/views/owners/show.html.erb</p>